name: ⚙️ CI
on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        name: ⬇️ Checkout repository
      - uses: oven-sh/setup-bun@v2
        name: 🛠️ Setup bun
        with:
          bun-version: latest
      - uses: actions/setup-node@v6
        name: 📦 Setup Node.js
        with:
          node-version: 23
      - name: 🔍 Install dependencies
        run: bun install --frozen-lockfile
      - name: 🧹 Lint
        run: bun run --filter=@pyyupsk/messenger-webhooks lint
      - name: 🏗️ Build
        run: bun run --filter=@pyyupsk/messenger-webhooks build
      - name: 🧪 Test
        run: bun run --filter=@repo/tests test
